### ISSUE TITLE
[Suggestion] Return Page Not Found If It Is Over The Pages Value In Config

### ISSUE THREAD

**Issue by Thunder33345** [Muqsit/Help#1]

**Comment by Muqsit** [comment]
In aware of this issue and it's likely PM 's fault

**Comment by Thunder33345** [comment]
i mean a suggestion
like overwrite the vanila /help cmd
by if $args[0] > $portect $ev->setcancelled(true) $p->sendMassage('Page Not Found')

**Comment by Muqsit** [comment]
Oh I gotcha

**Comment by Muqsit** [comment]
Here ya go: https://github.com/Muqsit/Help/tree/v1
